#!/bin/bash

# symlink .vimrc
if [ ! -f ~/.vimrc ]
then
  ln -s ~/.dotfiles/.vimrc ~/.vimrc
fi

# symlink .vimplugs.vimrc
if [ ! -f ~/.vimplugs.vimrc ]
then
  ln -s ~/.dotfiles/.vimplugs.vimrc ~/.vimplugs.vimrc
fi
