#!/bin/bash

# symlink .vimrc
[ -f ~/.vimrc ] && rm ~/.vimrc
ln -s ~/.dotfiles/.vimrc ~/.vimrc

# symlink .vimplugs.vimrc
[ -f ~/.vimplugs.vimrc ] && rm ~/.vimplugs.vimrc
ln -s ~/.dotfiles/.vimplugs.vimrc ~/.vimplugs.vimrc

# clean & install plugins
vim -c 'PlugClean|PlugInstall|q'

# install coc extensions
vim -c 'CocInstall -sync coc-tsserver coc-json coc-html coc-prettier coc-yaml \
  coc-solargraph coc-pairs coc-wxml coc-css coc-tslint coc-hightlight|q'

# symlink .alias
[ -f ~/.alias ] && rm ~/.alias
ln -s ~/.dotfiles/.alias ~/.alias

# symlink .ctags
[ -f ~/.ctags ] && rm ~/.ctags
ln -s ~/.dotfiles/.ctags ~/.ctags

# symlink .gitigore
[ -f ~/.gitignore ] && rm ~/.gitignore
ln -s ~/.dotfiles/.gitignore ~/.gitignore
