#!/bin/bash

# symlink .vimrc
if [ ! -f ~/.vimrc ]
then
  ln -s ~/.dotfiles/.vimrc ~/.vimrc
fi

# symlink .vimplugs.vimrc
if [ ! -f ~/.vimplugs.vimrc ]
then
  ln -s ~/.dotfiles/.vimplugs.vimrc ~/.vimplugs.vimrc
fi

# symlink .alias
[ -f ~/.alias ] && rm ~/.alias
ln -s ~/.dotfiles/.alias ~/.alias

# symlink .ctags
[ -f ~/.ctags ] && rm ~/.ctags
ln -s ~/.dotfiles/.ctags ~/.ctags

# symlink .gitigore
[ -f ~/.gitignore ] && rm ~/.gitignore
ln -s ~/.dotfiles/.gitignore ~/.gitignore
